name: Coleta Diária de Preços

on:
  schedule:
    - cron: '0 11 * * *'   # 08:00 Brasil
  workflow_dispatch:

jobs:
  coletar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar coleta de preços
        run: python coletor.py

      - name: Commitar banco atualizado
        run: |
          git config --global user.name "PriceRadar Bot"
          git config --global user.email "bot@priceradar.com"

          git add priceradar.db

          if ! git diff --cached --quiet; then
            git commit -m "chore: coleta diária $(date +'%Y-%m-%d')"
            git push
          else
            echo "Sem alterações no banco"
          fi
